### ISSUE TITLE
segmentation fault: 11

### ISSUE THREAD

**Issue by liuxc0116** [eycorsican/leaf#413]
版本: 55ed9a4
运行release版本在几小时或几天后会出现。segmentation fault: 11。（发现网络不好的时候容易出现）
我编译成Debug版本后。运行后几秒钟就会出现panic. 出现在下面两个位置。
第一：
`thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x10552969c', leaf/src/proxy/tun/netstack/udp.rs:49:28` 
panic的代码行是`let tot_len = unsafe { (*p).tot_len };`
完整代码如下:
```c
pub extern "C" fn udp_recv_cb(
    arg: *mut raw::c_void,
    _pcb: *mut udp_pcb,
    p: *mut pbuf,
    addr: *const ip_addr_t,
    port: u16_t,
    dst_addr: *const ip_addr_t,
    dst_port: u16_t,
) {
    let listener = unsafe { &mut *(arg as *mut UdpListener) };
    let src_addr = unsafe {
        match util::to_socket_addr(&*addr, port) {
            Ok(a) => a,
            Err(e) => {
                warn!("udp recv failed: {}", e);
                return;
            }
        }
    };
    let dst_addr = unsafe {
        match util::to_socket_addr(&*dst_addr, dst_port) {
            Ok(a) => a,
            Err(e) => {
                warn!("udp recv failed: {}", e);
                return;
            }
        }
    };

    let tot_len = unsafe { (*p).tot_len };
    let n = tot_len as usize;
    let mut buf = Vec::<u8>::with_capacity(n);
    unsafe {
        pbuf_copy_partial(p, buf.as_mut_ptr() as *mut raw::c_void, tot_len, 0);
        buf.set_len(n);
        pbuf_free(p);
    }

    match listener.queue.lock() {
        Ok(mut queue) => {
            let pkt = UdpPacket {
                data: (&buf[..n]).to_vec(),
                src_addr: Some(SocksAddr::Ip(src_addr)),
                dst_addr: Some(SocksAddr::Ip(dst_addr)),
            };
            queue.push_back(pkt);
            match listener.waker.lock() {
                Ok(waker) => {
                    if let Some(waker) = waker.as_ref() {
                        waker.wake_by_ref();
                    }
                }
                Err(err) => {
                    error!("udp waker lock waker failed {:?}", err);
                }
            }
        }
        Err(err) => {
            error!("udp listener lock queue failed {:?}", err);
        }
    }
}
```

第二
`thread 'tokio-runtime-worker' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x103cc3714', leaf/src/proxy/tun/netstack/output.rs:10:23`
panic的代码行是` let pbuflen = (*p).tot_len;`
完整代码如下:
```c
fn output(netif: *mut netif, p: *mut pbuf) -> err_t {
    unsafe {
        let pbuflen = (*p).tot_len;
        let mut buf = Vec::with_capacity((*netif).mtu as usize);
        pbuf_copy_partial(p, buf.as_mut_ptr() as *mut raw::c_void, pbuflen, 0);
        buf.set_len(pbuflen as usize);
        if OUTPUT_CB_PTR == 0x0 {
            return err_enum_t_ERR_ABRT as err_t;
        }
        let stack = &mut *(OUTPUT_CB_PTR as *mut NetStackImpl);
        let _ = stack.output((&buf[0..pbuflen as usize]).to_vec());
        err_enum_t_ERR_OK as err_t
    }
}
```

详细协议栈如下：
```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x10336569c', leaf/src/proxy/tun/netstack/udp.rs:49:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_misaligned_pointer_dereference
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/panicking.rs:174:5
   3: leaf::proxy::tun::netstack::udp::udp_recv_cb
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/netstack/udp.rs:49:28
   4: udp_input
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/netstack/lwip/core/udp.c:417:9
   5: ip4_input
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/netstack/lwip/core/ipv4/ip4.c:716:9
   6: ip_input
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/netstack/lwip/core/ip.c:160:12
   7: <leaf::proxy::tun::netstack::stack_impl::NetStackImpl as tokio::io::async_write::AsyncWrite>::poll_write
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/netstack/stack_impl.rs:404:27
   8: <alloc::boxed::Box<T> as tokio::io::async_write::AsyncWrite>::poll_write
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/io/async_write.rs:192:13
   9: <leaf::proxy::tun::netstack::stack::NetStack as tokio::io::async_write::AsyncWrite>::poll_write
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/netstack/stack.rs:47:9
  10: <tokio::io::split::WriteHalf<T> as tokio::io::async_write::AsyncWrite>::poll_write
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/io/split.rs:118:9
  11: <&mut T as tokio::io::async_write::AsyncWrite>::poll_write
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/io/async_write.rs:192:13
  12: <tokio::io::util::write::Write<W> as core::future::future::Future>::poll
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/io/util/write.rs:44:9
  13: leaf::proxy::tun::inbound::new::{{closure}}::{{closure}}
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/inbound.rs:129:79
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/future/future.rs:125:9
  15: futures_util::future::future::FutureExt::poll_unpin
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/future/mod.rs:562:9
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/select.rs:103:15
  17: leaf::proxy::tun::inbound::new::{{closure}}
             at /Users/agotoz/work/rust/leaf/leaf/src/proxy/tun/inbound.rs:145:42
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/future/future.rs:125:9
  19: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/maybe_done.rs:95:38
  20: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/join_all.rs:143:24
  21: leaf::start::{{closure}}
             at /Users/agotoz/work/rust/leaf/leaf/src/lib.rs:581:43
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/future/future.rs:125:9
  23: futures_util::future::future::FutureExt::poll_unpin
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/future/mod.rs:562:9
  24: <futures_util::future::select_all::SelectAll<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/select_all.rs:55:78
  25: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/traits/iterator.rs:2806:32
  26: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::{{closure}}
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/adapters/enumerate.rs:86:27
  27: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/traits/iterator.rs:2310:21
  28: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/adapters/enumerate.rs:92:9
  29: core::iter::traits::iterator::Iterator::find_map
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/traits/iterator.rs:2812:9
  30: <futures_util::future::select_all::SelectAll<Fut> as core::future::future::Future>::poll
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.19/src/future/select_all.rs:55:20
  31: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/park/thread.rs:263:54
  32: tokio::coop::with_budget::{{closure}}
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/coop.rs:102:9
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/thread/local.rs:252:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/thread/local.rs:228:9
  35: tokio::coop::with_budget
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/coop.rs:95:5
  36: tokio::coop::budget
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/coop.rs:72:5
  37: tokio::park::thread::CachedParkThread::block_on
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/park/thread.rs:263:31
  38: tokio::runtime::enter::Enter::block_on
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/runtime/enter.rs:151:13
  39: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/runtime/thread_pool/mod.rs:77:9
  40: tokio::runtime::Runtime::block_on
             at /Users/agotoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.15.0/src/runtime/mod.rs:463:43
```

**Comment by liuxc0116** [comment]
看报错应该是`p: *mut pbuf` 这个参数值为null。导致访问了未知内存

**Comment by eycorsican** [comment]
应该已经在这里修好了：https://github.com/eycorsican/netstack-lwip/commit/cb5c81d50fb529ff520d7a722e434434160cf73a

`cargo update` 一下再重新编译吧。

**Comment by liuxc0116** [comment]
> 应该已经在这里修好了：[eycorsican/netstack-lwip@cb5c81d](https://github.com/eycorsican/netstack-lwip/commit/cb5c81d50fb529ff520d7a722e434434160cf73a)
> 
> `cargo update` 一下再重新编译吧。
嗯嗯， 对于segmentation fault: 11，有什么好的排查建议吗。

**Comment by liuxc0116** [comment]
> 应该已经在这里修好了：[eycorsican/netstack-lwip@cb5c81d](https://github.com/eycorsican/netstack-lwip/commit/cb5c81d50fb529ff520d7a722e434434160cf73a)
> 
> `cargo update` 一下再重新编译吧。

嗯嗯， 对于segmentation fault: 11，有什么好的排查建议吗。

**Comment by eycorsican** [comment]
> > 应该已经在这里修好了：[eycorsican/netstack-lwip@cb5c81d](https://github.com/eycorsican/netstack-lwip/commit/cb5c81d50fb529ff520d7a722e434434160cf73a)
> > `cargo update` 一下再重新编译吧。
> 
> 嗯嗯， 对于segmentation fault: 11，有什么好的排查建议吗。

运行debug build复现后看日志或者用gdb调试
