### ISSUE TITLE
错误消息表明找不到com.sail_tunnel.sail.services.TunnelInstance.leafRun(int, java.lang.String)方法的实现。

### ISSUE THREAD

**Issue by jianchao123** [eycorsican/leaf#440]
**E/AndroidRuntime( 5343): java.lang.UnsatisfiedLinkError: No implementation found for void com.sail_tunnel.sail.services.TunnelInstance.leafRun(int, java.lang.String) (tried Java_com_sail_1tunnel_sail_services_TunnelInstance_leafRun 
and Java_com_sail_1tunnel_sail_services_TunnelInstance_leafRun__ILjava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
E/AndroidRuntime( 5343):        at com.sail_tunnel.sail.services.TunnelInstance.leafRun(Native Method)
E/AndroidRuntime( 5343):        at com.sail_tunnel.sail.services.TunnelInstance.access$leafRun(TunnelInstance.kt:15)
E/AndroidRuntime( 5343):        at com.sail_tunnel.sail.services.TunnelInstance$start$2.invoke(TunnelInstance.kt:88)
E/AndroidRuntime( 5343):        at com.sail_tunnel.sail.services.TunnelInstance$start$2.invoke(TunnelInstance.kt:87)
E/AndroidRuntime( 5343):        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)**

**错误消息表明找不到com.sail_tunnel.sail.services.TunnelInstance.leafRun(int, java.lang.String)方法的实现。我下载的v0.10.7版本的库文件:[leaf-x86_64-unknown-linux-musl.gz]**

**Comment by jianchao123** [comment]
额，我本来想下载安卓的库，但是[leaf-android-libs.zip]该压缩包里面只有一个.h的头文件
